package com.frikinjay.mobstacker.config;

import java.util.ArrayList;
import java.util.List;
import java.util.function.Consumer;
import java.util.function.Function;
import java.util.function.Supplier;

/**
 * A single, data-driven description of one configurable setting.
 * <p>
 * One {@code ConfigOption} bundles everything the rest of the mod needs to expose a setting
 * without hand-writing per-setting code: its stable user-facing {@code id} (the token typed after
 * {@code /mobstacker set}; the JSON config format is untouched), its {@link Category} and
 * {@link Type}, a human description, the getter/setter onto {@link MobStackerConfig}, numeric
 * bounds, a default value and optional
 * validation. Both the command layer ({@code /mobstacker set|get|toggle|reset}) and the future
 * config GUI are generated by iterating over the {@link MobStackerSettings} registry of these,
 * so a new setting only has to be declared once.
 */
public final class ConfigOption {
    public enum Type { BOOL, INT, DOUBLE, ENUM, STRING, ITEM }

    public enum Category {
        STACKING("Stacking"),
        COMBAT("Combat"),
        FEEDBACK("Kill feedback"),
        DISPLAY("Stack display"),
        BREEDING("Breeding"),
        DROPS("Drops & XP"),
        MOBCAPS("Mob caps"),
        SEPARATOR("Separator");

        private final String display;

        Category(String display) {
            this.display = display;
        }

        public String display() {
            return display;
        }
    }

    /** Outcome of applying a new value, so callers can give consistent feedback. */
    public static final class Result {
        public enum Status { CHANGED, UNCHANGED, ERROR }

        public final Status status;
        public final String message;
        public final String oldValue;
        public final String newValue;

        private Result(Status status, String message, String oldValue, String newValue) {
            this.status = status;
            this.message = message;
            this.oldValue = oldValue;
            this.newValue = newValue;
        }

        static Result changed(String oldValue, String newValue, String note) {
            return new Result(Status.CHANGED, note, oldValue, newValue);
        }

        static Result unchanged(String value) {
            return new Result(Status.UNCHANGED, null, value, value);
        }

        static Result error(String message) {
            return new Result(Status.ERROR, message, null, null);
        }
    }

    private final String id;
    private final Category category;
    private final Type type;
    private final String description;
    private final Supplier<Object> getter;
    private final Consumer<Object> setter;
    private final Function<String, Object> parser;
    private final Object defaultValue;
    private final Double min;
    private final Double max;
    private final List<String> enumValues;
    // Optional: given the proposed (parsed) value, return an error message or null if valid.
    private Function<Object, String> validator;
    // Optional: the id of a boolean setting that must be on before this one can be changed away from
    // its default. Resolved where the change is made, so a region uses its own value for it.
    private String requires;
    // Optional: the id of a boolean setting that, while it is on, pins this one to "true". Unlike
    // `requires` this is not a "does nothing" hint but a hard lock: the value cannot be changed at
    // all until the other setting is off again. Also resolved where the change is made.
    private String lockedOnBy;
    // Optional: the id of a boolean setting that, while it is on, already does what this one asks
    // for — so this one cannot change anything. The third shape, and the mildest: nothing is forced
    // and nothing is required, the setting is simply inert. Also resolved where it is read.
    private String redundantWhen;
    // Optional: after a successful change, return an extra info note (e.g. a forced dependency) or null.
    private Supplier<String> appliedNote;

    private ConfigOption(String id, Category category, Type type, String description,
                         Supplier<Object> getter, Consumer<Object> setter, Function<String, Object> parser,
                         Object defaultValue, Double min, Double max, List<String> enumValues) {
        this.id = id;
        this.category = category;
        this.type = type;
        this.description = description;
        this.getter = getter;
        this.setter = setter;
        this.parser = parser;
        this.defaultValue = defaultValue;
        this.min = min;
        this.max = max;
        this.enumValues = enumValues;
    }

    // --- Metadata accessors ---

    public String id() { return id; }
    public Category category() { return category; }
    public Type type() { return type; }
    public String description() { return description; }
    public Double min() { return min; }
    public Double max() { return max; }
    public List<String> enumValues() { return enumValues; }

    /**
     * Current value formatted as a canonical string (e.g. {@code "true"}, {@code "16"},
     * {@code "REGIONS"}) — what the game actually acts on. A setting another one pins reports the
     * pinned value, and one whose dependency is off reports its default, because until that
     * dependency comes back on it does nothing. The value stored underneath is untouched either way
     * and returns as soon as the setting it hangs on changes.
     */
    public String currentValue() {
        String effective = MobStackerSettings.effectiveValue(this, null);
        return effective != null ? effective : storedValue();
    }

    /** The value actually stored in the config, whatever another setting currently makes of it. */
    public String storedValue() {
        return String.valueOf(getter.get());
    }

    /** The default value formatted as a canonical string. */
    public String defaultValue() {
        return String.valueOf(defaultValue);
    }

    /** Typed current value, for the GUI (Boolean / Integer / Double / Enum / String). */
    public Object rawValue() {
        return getter.get();
    }

    // --- Suggestions for tab-completion / GUI widgets ---

    /**
     * Values worth suggesting for this option's argument. Empty for free-form numeric/string types
     * (item ids are suggested separately from the live registry by the command layer).
     */
    /**
     * What a player types instead of looking a number up: {@code set maxStackSize max} is the
     * largest that setting goes, whatever that happens to be. It is stored as the number it means,
     * so what comes back out of {@code get} is unambiguous and the config file stays plain.
     */
    public static final String MAX_KEYWORD = "max";

    /**
     * Reads a size somebody typed, accepting {@link #MAX_KEYWORD}. For the per-type stack ceilings,
     * which are not settings and so never pass through {@link #apply} - the word has to mean the
     * same thing there as it does everywhere else.
     *
     * @return the number, or null when it is neither a whole number nor {@code max}
     */
    public static Integer parseSize(String raw) {
        String text = raw == null ? "" : raw.trim();
        if (text.isEmpty()) {
            return null;
        }
        if (MAX_KEYWORD.equalsIgnoreCase(text)) {
            return Integer.MAX_VALUE;
        }
        try {
            return Integer.parseInt(text);
        } catch (NumberFormatException e) {
            return null;
        }
    }

    public List<String> valueSuggestions() {
        List<String> out = new ArrayList<>();
        switch (type) {
            case BOOL -> {
                out.add("true");
                out.add("false");
            }
            case ENUM -> {
                for (String value : enumValues) {
                    out.add(value.toLowerCase());
                }
            }
            case INT, DOUBLE -> {
                out.add(currentValue());
                out.add(defaultValue());
                out.add(MAX_KEYWORD);
            }
            default -> {
                // STRING / ITEM: no fixed set here.
            }
        }
        return out;
    }

    // --- Mutation ---

    /**
     * Parses, validates and applies {@code raw}. Never throws; problems come back as
     * {@link Result.Status#ERROR}. Unchanged values report {@link Result.Status#UNCHANGED}.
     */
    public Result apply(String raw) {
        Object parsed;
        try {
            parsed = parser.apply(raw);
        } catch (IllegalArgumentException e) {
            return Result.error(e.getMessage());
        }

        if (validator != null) {
            String problem = validator.apply(parsed);
            if (problem != null) {
                return Result.error(problem);
            }
        }

        // Judged on what is stored, not on what the setting currently reads as: a setting held at
        // its default by a dependency must still be resettable, and `set` changes the stored value.
        String oldValue = storedValue();
        String newValue = String.valueOf(parsed);

        // A locked setting cannot be changed at all while whatever pins it is on - and that is
        // judged before the "nothing to do" shortcut below, against what the setting READS AS.
        // stackHealth holds killWholeStackOnDeath on while false is still what sits in the file, so
        // comparing stored values first answered "it is already false" to a player looking at a
        // switch that says ON. A request that matches what it reads as really is a no-op and still
        // passes through as unchanged.
        String lock = MobStackerSettings.lockProblem(this, null, null);
        if (lock != null) {
            return newValue.equalsIgnoreCase(currentValue())
                    ? Result.unchanged(currentValue())
                    : Result.error(lock);
        }

        if (oldValue.equals(newValue)) {
            return Result.unchanged(oldValue);
        }

        // A setting that depends on another one may always be switched off - its default, or the
        // value that means it does nothing, whichever way round they are - but only turned on once
        // the setting it needs is on.
        if (!newValue.equalsIgnoreCase(defaultValue())
                && !newValue.equalsIgnoreCase(MobStackerSettings.inertValue(this))) {
            String problem = MobStackerSettings.dependencyProblem(this, null, null);
            if (problem != null) {
                return Result.error(problem);
            }
        }

        setter.accept(parsed);
        String actualNew = storedValue();
        String note = appliedNote != null ? appliedNote.get() : null;
        return Result.changed(oldValue, actualNew, note);
    }

    /**
     * Parses and validates {@code raw} without changing anything, returning it in the same canonical
     * form {@link #currentValue()} uses. This is what lets a value be stored somewhere other than the
     * global config - a region's own settings - while still being checked exactly like a global edit.
     *
     * @throws IllegalArgumentException with a message fit for a player, when the value is not usable
     */
    public String canonicalize(String raw) {
        Object parsed = parser.apply(raw);
        if (validator != null) {
            String problem = validator.apply(parsed);
            if (problem != null) {
                throw new IllegalArgumentException(problem);
            }
        }
        return String.valueOf(parsed);
    }

    /** Flips a boolean option. Errors for any non-boolean type. */
    public Result toggle() {
        if (type != Type.BOOL) {
            return Result.error("'" + id + "' is not a toggle (it is a " + type + " setting)");
        }
        boolean current = (Boolean) getter.get();
        return apply(String.valueOf(!current));
    }

    /** Restores the option to its default value. */
    public Result reset() {
        return apply(String.valueOf(defaultValue));
    }

    // --- Optional wiring ---

    public ConfigOption withValidator(Function<Object, String> validator) {
        this.validator = validator;
        return this;
    }

    /**
     * Declares that this setting does nothing until {@code settingId} (a boolean setting) is on. It
     * then reads as its own default and refuses to be changed, and the config GUI greys it out, so a
     * switch can never sit on {@code ON} while having no effect. Whatever was stored is kept and
     * comes back when {@code settingId} does. Unlike a validator this is metadata, which lets it be
     * resolved against a region's own value rather than only the global one — see
     * {@link MobStackerSettings#dependencyProblem}.
     */
    public ConfigOption requires(String settingId) {
        this.requires = settingId;
        return this;
    }

    /** The setting that has to be on for this one to work, or null when it stands alone. */
    public String requires() {
        return requires;
    }

    /**
     * Declares that this setting is forced on — and cannot be changed — while {@code settingId} (a
     * boolean setting) is on, the way {@code stackHealth} needs {@code killWholeStackOnDeath}. The
     * value stored underneath is left alone, so switching {@code settingId} off hands the player
     * their own choice back instead of silently keeping the forced one.
     */
    public ConfigOption lockedOnBy(String settingId) {
        this.lockedOnBy = settingId;
        return this;
    }

    /** The setting that pins this one to "true" while it is on, or null when nothing does. */
    public String lockedOnBy() {
        return lockedOnBy;
    }

    /**
     * Declares that this setting cannot change anything while {@code settingId} (a boolean setting)
     * is on, because that setting already produces the same result — the way
     * {@code killWholeStackOnDeath} already puts the whole sweep into one hit, which is all
     * {@code sweepingEdgeSingleHit} has to offer.
     *
     * <p>The third dependency shape, and the mildest of the three: {@link #lockedOnBy(String)} pins a
     * value, {@link #requires(String)} says "not yet", and this one says "no longer needed". It is
     * treated like {@code requires} where it counts — the setting reads as its own default and the
     * GUI greys it out with the reason — because the rule they both serve is that a switch must
     * never sit on {@code ON} while having no effect.
     */
    public ConfigOption redundantWhen(String settingId) {
        this.redundantWhen = settingId;
        return this;
    }

    /** The setting that makes this one pointless while it is on, or null when nothing does. */
    public String redundantWhen() {
        return redundantWhen;
    }

    public ConfigOption withAppliedNote(Supplier<String> appliedNote) {
        this.appliedNote = appliedNote;
        return this;
    }

    // --- Factories ---

    @SuppressWarnings("unchecked")
    public static ConfigOption ofBool(String id, Category category, String description,
                                      Supplier<Boolean> getter, Consumer<Boolean> setter, boolean defaultValue) {
        return new ConfigOption(id, category, Type.BOOL, description,
                (Supplier<Object>) (Supplier<?>) getter,
                value -> setter.accept((Boolean) value),
                ConfigOption::parseBool,
                defaultValue, null, null, null);
    }

    @SuppressWarnings("unchecked")
    public static ConfigOption ofInt(String id, Category category, String description,
                                     int min, int max, Supplier<Integer> getter, Consumer<Integer> setter, int defaultValue) {
        return new ConfigOption(id, category, Type.INT, description,
                (Supplier<Object>) (Supplier<?>) getter,
                value -> setter.accept((Integer) value),
                raw -> parseInt(raw, id, min, max),
                defaultValue, (double) min, (double) max, null);
    }

    @SuppressWarnings("unchecked")
    public static ConfigOption ofDouble(String id, Category category, String description,
                                        double min, double max, Supplier<Double> getter, Consumer<Double> setter, double defaultValue) {
        return new ConfigOption(id, category, Type.DOUBLE, description,
                (Supplier<Object>) (Supplier<?>) getter,
                value -> setter.accept((Double) value),
                raw -> parseDouble(raw, id, min, max),
                defaultValue, min, max, null);
    }

    @SuppressWarnings("unchecked")
    public static <E extends Enum<E>> ConfigOption ofEnum(String id, Category category, String description,
                                                          Class<E> enumClass, Supplier<E> getter, Consumer<E> setter, E defaultValue) {
        List<String> values = new ArrayList<>();
        for (E constant : enumClass.getEnumConstants()) {
            values.add(constant.name());
        }
        return new ConfigOption(id, category, Type.ENUM, description,
                (Supplier<Object>) (Supplier<?>) getter,
                value -> setter.accept(enumClass.cast(value)),
                raw -> parseEnum(raw, id, enumClass),
                defaultValue, null, null, values);
    }

    /**
     * A free-form string. {@code isItem} switches suggestions/validation to Minecraft item ids;
     * validation of item existence is supplied by the caller via {@link #withValidator}.
     */
    @SuppressWarnings("unchecked")
    public static ConfigOption ofString(String id, Category category, String description, boolean isItem,
                                         Supplier<String> getter, Consumer<String> setter, String defaultValue) {
        return new ConfigOption(id, category, isItem ? Type.ITEM : Type.STRING, description,
                (Supplier<Object>) (Supplier<?>) getter,
                value -> setter.accept((String) value),
                raw -> raw,
                defaultValue, null, null, null);
    }

    // --- Parsers ---

    private static Object parseBool(String raw) {
        if ("true".equalsIgnoreCase(raw)) return Boolean.TRUE;
        if ("false".equalsIgnoreCase(raw)) return Boolean.FALSE;
        throw new IllegalArgumentException("Expected true or false, got '" + raw + "'");
    }

    private static Object parseInt(String raw, String id, int min, int max) {
        int value;
        if (MAX_KEYWORD.equalsIgnoreCase(raw.trim())) {
            return max;
        }
        try {
            value = Integer.parseInt(raw.trim());
        } catch (NumberFormatException e) {
            throw new IllegalArgumentException("'" + raw + "' is not a whole number (or '"
                    + MAX_KEYWORD + "')");
        }
        if (value < min || value > max) {
            throw new IllegalArgumentException(id + " must be between " + min + " and " + max);
        }
        return value;
    }

    private static Object parseDouble(String raw, String id, double min, double max) {
        double value;
        if (MAX_KEYWORD.equalsIgnoreCase(raw.trim())) {
            return max;
        }
        try {
            value = Double.parseDouble(raw.trim());
        } catch (NumberFormatException e) {
            throw new IllegalArgumentException("'" + raw + "' is not a number (or '"
                    + MAX_KEYWORD + "')");
        }
        if (value < min || value > max) {
            throw new IllegalArgumentException(id + " must be between " + min + " and " + max);
        }
        return value;
    }

    private static <E extends Enum<E>> Object parseEnum(String raw, String id, Class<E> enumClass) {
        for (E constant : enumClass.getEnumConstants()) {
            if (constant.name().equalsIgnoreCase(raw)) {
                return constant;
            }
        }
        StringBuilder allowed = new StringBuilder();
        for (E constant : enumClass.getEnumConstants()) {
            if (allowed.length() > 0) allowed.append(", ");
            allowed.append(constant.name().toLowerCase());
        }
        throw new IllegalArgumentException("Invalid value for " + id + "; expected one of: " + allowed);
    }
}
